# Julia Basics

## Variables

In [1]:
x = 99
x, typeof(x)

(99, Int64)

In [2]:
y = 10.0
y, typeof(y)

(10.0, Float64)

In [3]:
s = "Data Science"
s, typeof(s)

("Data Science", String)

In [4]:
t = true
t, typeof(t)

(true, Bool)

## Operators

In [5]:
p = 2
q = 3
r = 4
p, q, r

(2, 3, 4)

### Arithmetic Operators

In [6]:
r / p

2.0

In [7]:
p * q

6

In [8]:
p + q

5

In [9]:
r - q

1

In [10]:
q - r

-1

In [11]:
q ^ p

9

### Comparison Operators

In [12]:
p == p

true

In [13]:
p == q

false

In [14]:
p != q

true

In [15]:
p >= q

false

In [16]:
p > q

false

In [17]:
p <= q

true

In [18]:
p < q

true

## Data Types

### Integers

In [19]:
int_16 = Int16(16)
int_16, typeof(int_16), typemax(Int16)

(16, Int16, 32767)

In [20]:
int_32 = Int32(32)
int_32, typeof(int_32), typemax(Int32)

(32, Int32, 2147483647)

In [21]:
int_64 = Int64(64)
int_64, typeof(int_64), typemax(Int64)

(64, Int64, 9223372036854775807)

In [22]:
int_128 = Int64(128)
int_128, typeof(int_128), typemax(Int128)

(128, Int64, 170141183460469231731687303715884105727)

### Floats

In [23]:
float_16 = Float16(16.0)
float_16, typeof(float_16), typemax(Float16)

(Float16(16.0), Float16, Inf16)

In [24]:
float_32 = Float32(32.0)
float_32, typeof(float_32), typemax(Float32)

(32.0f0, Float32, Inf32)

In [25]:
float_64 = Float64(64.0)
float_64, typeof(float_64), typemax(Float64)

(64.0, Float64, Inf)

### Numeric checks

In [26]:
isinf(1/0)

true

In [27]:
isinf(-1/0)

true

In [28]:
isnan(0/0)

true

### Strings

In [29]:
s1 = "Data Science"

"Data Science"

In [30]:
s2 = "I'm learning Data Science"

"I'm learning Data Science"

In [31]:
s2[1]

'I': ASCII/Unicode U+0049 (category Lu: Letter, uppercase)

In [32]:
s2[end]

'e': ASCII/Unicode U+0065 (category Ll: Letter, lowercase)

In [33]:
s2[2:6]

"'m le"

In [34]:
s2[end-6:end]

"Science"

In [35]:
s2 * ". It's fun!"

"I'm learning Data Science. It's fun!"

In [36]:
"1 + 2 = $(1 + 2)"

"1 + 2 = 3"

In [37]:
"$x + $y = $(x + y)"

"99 + 10.0 = 109.0"

In [38]:
length(s2)

25

In [39]:
findfirst("Data", s2)

14:17

In [40]:
s3 = "pqrs"
s4 = "pqrt"
s3, s4

("pqrs", "pqrt")

In [41]:
s3 == s4

false

In [42]:
s3 > s4

false

In [43]:
s3 < s4

true

### Tuples

In [44]:
t1 = (1, 2, 3, 4)
t1, typeof(t1)

((1, 2, 3, 4), NTuple{4, Int64})

In [45]:
t2 = ("Data", 1, 2.0)
t2, typeof(t2)

(("Data", 1, 2.0), Tuple{String, Int64, Float64})

In [46]:
u, v, w = t2
u

"Data"

### Arrays

In [47]:
a1 = Array{Int64}(undef, 3) # vector of length 3
a1, typeof(a1)

([140657856251184, 140657856251104, 140657853053888], Vector{Int64})

In [48]:
a2 = Array{Int64}(undef, (3,2)) # 3 x 2 matrix
a2, typeof(a2)

([140658581916000 140658487799840; 140658582655744 140658581916016; 140657812709680 140658487767216], Matrix{Int64})

In [49]:
a3 = [1,2,3]
a3

3-element Vector{Int64}:
 1
 2
 3

In [50]:
a4 = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [51]:
a5 = [1 2 3 ; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [52]:
a6 = [1 2 3 ; 4 5 6 ; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [53]:
zeros((2,2))

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [54]:
zeros(Float64, (2,2))

2×2 Matrix{Float64}:
 0.0  0.0
 0.0  0.0

In [55]:
ones((2,2))

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [56]:
ones(Float64, (2,2))

2×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0

In [57]:
rand(Int64, (2,2))

2×2 Matrix{Int64}:
  515948280827261223  2718871008090965116
 1435386932706634617   -56964128202180136

In [58]:
randn((2,2))

2×2 Matrix{Float64}:
 -0.0287054   1.70701
  0.834892   -0.275577

### Dictionaries

In [59]:
d0 = Dict("id" => 100, "age" => 24)

Dict{String, Int64} with 2 entries:
  "id"  => 100
  "age" => 24

In [60]:
d0["id"]

100

In [61]:
d0["age"]

24

In [62]:
d0["level"] = 1
d0

Dict{String, Int64} with 3 entries:
  "id"    => 100
  "age"   => 24
  "level" => 1

In [63]:
haskey(d0, "id")

true

In [64]:
delete!(d0, "level")
d0

Dict{String, Int64} with 2 entries:
  "id"  => 100
  "age" => 24